### ISSUE TITLE
Low number of sequences classified in human metagenome samples

### ISSUE THREAD

**Issue by TakacsBertalan** [sunbeam-labs/sunbeam#282]
Hi!
I am using Sunbeam to analyze human metagenome samples (feces and nasal) and at the classification step, kraken2 seems to only classify a very low number of sequences: if the database contains only bacteria, viruses and fungi the percentage of the classified sequences is 0.5-5%, using kraken2 standard database classifies 40% of the sequences. Is there any way to tell why the rest wasn't classified and get the unclassified sequences?
I am using the newset sunbeam-dev version, with the newest version of kraken2. My contig file looks like this
```
# 
# Sunbeam configuration file
#
# Defining samples:
#   Run 'sunbeam list_samples <data_dir>' to create a list of samples and
#   associated fastq.gz files. Samples must be in gzipped fastq format.
#
# Paths:
#   Paths are resolved through the following rules:
#     1. If the path is absolute, the path is parsed as-is
#     2. If the path is not absolute, the path at 'root' is appended to it
#     3. If the path is not 'output_fp', the path is checked to ensure it exists
#
# Suffixes:
#   Each subsection contains a 'suffix' key that defines the folder under
#   'output_fp' where the results of that section are put.
#

# General options
all:
  root: /media/data/Sunbeam/sunbeam-dev/cosmosid
  output_fp: sunbeam_output
  samplelist_fp: samples.csv
  paired_end: true
  download_reads: false
  version: 2.1.1+dev0.g43432e1.d20200819

# Quality control
qc:
  suffix: qc
  # Trimmomatic
  threads: 4
  java_heapsize: 512M
  leading: 3
  trailing: 3
  slidingwindow: [4, 15]
  minlen: 36
  adapter_fp: /home/deltagene/anaconda3/envs/sunbeam/share/trimmomatic/adapters/NexteraPE-PE.fa
  # Cutadapt
  fwd_adapters: [GTTTCCCAGTCACGATC, GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC]
  rev_adapters: [GTTTCCCAGTCACGATC, GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC]
  # Komplexity
  kz_threshold: 0.55
  # Decontam.py
  pct_id: 0.5
  frac: 0.6
  host_fp: ''


# Taxonomic classifications
  seq_id_ending: /[12]
  adapter_template: /home/deltagene/anaconda3/envs/sunbeam/share/trimmomatic/adapters/NexteraPE-PE.fa
classify:
  suffix: classify
  threads: 8
  kraken_db_fp: /media/data/Sunbeam/standard_kraken2

# Contig assembly
assembly:
  suffix: assembly
  min_length: 300
  threads: 4

# Contig annotation
annotation:
  suffix: annotation
  min_contig_len: 500
  circular_kmin: 10
  circular_kmax: 1000
  circular_min_len: 3500

blast:
  threads: 4

blastdbs:
  root_fp: /media/data/Sunbeam/blast_db
  nucleotide:
    nt: nt/original_nt
    
mapping:
  suffix: mapping
  genomes_fp: ''
  samtools_opts: ''
  threads: 4

download:
  suffix: download
  threads: 4:
```
The kraken2 result: 
```
Loading database information... done.
5956849 sequences (1678.57 Mbp) processed in 142.406s (2509.8 Kseq/m, 707.23 Mbp/m).
  2592890 sequences classified (43.53%)
  3363959 sequences unclassified (56.47%)
```
