### ISSUE TITLE
allow relative path for sunbeam_config.yml

### ISSUE THREAD

**Issue by scottdaniel** [sunbeam-labs/sunbeam#397]
**What's the feature?**
In the config.yaml you have to put the absolute path of the sunbeam_config.yml
This would allow it to simply look in the directory where the config.yaml already resides

e.g.
configfile: "sunbeam4_config.yml" # would be nice if you could do it like this
instead of...
configfile: "/mnt/isilon/microbiome/analysis/danielsg/redding_run_4/Scripts/HPC_cluster/sunbeam4_config.yml"

**Comment by Ulthran** [comment]
Hi Scott,

Just tested this out and it seems like it probably won't work. The path has to relative to a sunbeamlib script it's read into instead of `config.yaml`.

`sunbeam init` should fill this in automatically for you though. I think we talked at some point about making a template file for the team so that you could use `sunbeam init` instead of copy/pasting.

e.g. this is an old pmacs template:

```
qc:
  human_genome_fp: "/project/bushmanlab/indexes/GCA_000001405.15_GRCh38_genomic.fna"
  phix_genome_fp: "/project/bushmanlab/indexes/phix174.fasta"

classify:
  kraken_db_fp: "/project/bushmanlab/kraken/standard"

blastdbs:
  root_fp: "/project/bushmanlab/genomeIndexes/blast"
  nucleotide:
    nt: nt/nt
```

Make a file like this with all the default values you want specified or overridden and then use `sunbeam init --defaults /path/to/defaults/file.yml ...`.
