### ISSUE TITLE
Unable to load config

### ISSUE THREAD

**Issue by levlitichev** [sunbeam-labs/sunbeam#409]
Hi Charlie,

Just downloaded Sunbeam v4. Installation was straightforward and correctly dealt with my pre-existing conda and mamba installs. All tests passed and were easy to use. Nice!

But then I hit a snag reading in the config file. Here is my attempt at a reprex.

First, here is my setup:

```
(sunbeam4.0.0) [litichev@node157 2023-08-24_sunbeam_config_reprex]$ pwd
/home/litichev/2023-08-24_sunbeam_config_reprex
(sunbeam4.0.0) [litichev@node157 2023-08-24_sunbeam_config_reprex]$ ls
samples_mini.csv  sunbeam_config.yml
(sunbeam4.0.0) [litichev@node157 2023-08-24_sunbeam_config_reprex]$ cat samples_mini.csv
S1,/path/to/S1.fastq
S2,/path/to/S2.fastq
(sunbeam4.0.0) [litichev@node157 2023-08-24_sunbeam_config_reprex]$ cat sunbeam_config.yml
all:
  root: /home/litichev/2023-08-24_sunbeam_config_reprex/
  output_fp: sunbeam_output
  samplelist_fp: samples_mini.csv
  paired_end: false
  version: 4.0.0
qc:
  suffix: qc
  leading: 3
  trailing: 3
  slidingwindow: [4, 15]
  minlen: 36
  adapter_template: $CONDA_PREFIX/share/trimmomatic/adapters/NexteraPE-PE.fa
  fwd_adapters: [GTTTCCCAGTCACGATC, GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC]
  rev_adapters: [GTTTCCCAGTCACGATC, GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC]
  cutadapt_opts: "--discard-trimmed"
  kz_threshold: 0.55
  pct_id: 0.5
  frac: 0.6
  host_fp: ''
classify:
  suffix: classify
assembly:
  suffix: assembly
annotation:
  suffix: annotation
blastdbs:
  root_fp: ''
mapping:
  suffix: mapping
benchmarks:
  suffix: benchmarks
logs:
  suffix: logs
```

I also have a snakemake profile for LSF that I have used successfully in the past. It's located at `~/.config/snakemake/lsf/`.

And here is the first command I tried to run:

```
(sunbeam4.0.0) [litichev@node157 2023-08-24_sunbeam_config_reprex]$ sunbeam run --profile lsf -n all_qc
Running: snakemake --snakefile /home/litichev/sunbeam_v4/workflow/Snakefile --conda-prefix /home/litichev/sunbeam_v4/.snakemake --profile lsf -n all_qc
Using profile lsf for setting default command line arguments.
SystemExit in file /home/litichev/sunbeam_v4/workflow/Snakefile, line 34:
Config not found, are you sure your profile contains a path to an existing configfile?
  File "/home/litichev/sunbeam_v4/workflow/Snakefile", line 34, in <module>
```

Let me know what you think.

Thanks very much,
Lev
